-- migration_v8.sql
-- v1.16.10: 누락된 컬럼 추가 + GENERATED ALWAYS → BY DEFAULT AS IDENTITY 변경

-- 1. bills 테이블에 복지할인/전기수도 상세 컬럼 추가
ALTER TABLE bills ADD COLUMN IF NOT EXISTS welfare_type TEXT DEFAULT 'none';
ALTER TABLE bills ADD COLUMN IF NOT EXISTS welfare_deduction NUMERIC DEFAULT 0;
ALTER TABLE bills ADD COLUMN IF NOT EXISTS water_deduction NUMERIC DEFAULT 0;
ALTER TABLE bills ADD COLUMN IF NOT EXISTS elec_cost NUMERIC DEFAULT 0;
ALTER TABLE bills ADD COLUMN IF NOT EXISTS water_cost NUMERIC DEFAULT 0;

-- 2. contracts 테이블에 file_type 컬럼 추가
ALTER TABLE contracts ADD COLUMN IF NOT EXISTS file_type TEXT DEFAULT '';

-- 3. maintenance_categories — GENERATED ALWAYS → BY DEFAULT (클라이언트 ID upsert 허용)
ALTER TABLE maintenance_categories ALTER COLUMN id DROP IDENTITY IF EXISTS;
ALTER TABLE maintenance_categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
