-- Supabase 마이그레이션 - 간석로1545 v1.11.0
-- Supabase Dashboard → SQL Editor → 붙여넣기 → Run

-- 1. users (Supabase Auth 연동)
CREATE TABLE IF NOT EXISTS users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  auth_id uuid UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
  username text UNIQUE NOT NULL,
  name text NOT NULL DEFAULT '',
  email text UNIQUE,
  phone text DEFAULT '',
  role text NOT NULL DEFAULT 'tenant' CHECK (role IN ('admin','manager','tenant')),
  unit_id bigint,
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('active','pending')),
  created_at timestamptz DEFAULT now()
);
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can read own data" ON users FOR SELECT USING (auth.uid() = auth_id OR role = 'admin');
CREATE POLICY "Admins can insert/update/delete" ON users FOR ALL USING (auth.jwt() ->> 'role' = 'admin');

-- 2. buildings
CREATE TABLE IF NOT EXISTS buildings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL DEFAULT '',
  address text DEFAULT '',
  memo text DEFAULT '',
  admin_name text DEFAULT '',
  admin_phone text DEFAULT '',
  admin_email text DEFAULT '',
  bank_name text DEFAULT '',
  account_holder text DEFAULT '',
  account_number text DEFAULT ''
);
ALTER TABLE buildings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Authenticated users can CRUD" ON buildings FOR ALL USING (auth.role() = 'authenticated');

-- 3. units
CREATE TABLE IF NOT EXISTS units (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL DEFAULT '',
  building_id bigint REFERENCES buildings(id) ON DELETE SET NULL,
  area numeric DEFAULT 0,
  has_ac boolean DEFAULT false,
  has_tv boolean DEFAULT false,
  has_fridge boolean DEFAULT false,
  has_washer boolean DEFAULT false,
  has_tv_stand boolean DEFAULT false,
  has_bed boolean DEFAULT false,
  has_closet boolean DEFAULT false
);
ALTER TABLE units ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Authenticated users can CRUD" ON units FOR ALL USING (auth.role() = 'authenticated');

-- 4. contracts
CREATE TABLE IF NOT EXISTS contracts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  unit_id bigint REFERENCES units(id) ON DELETE CASCADE,
  tenant text DEFAULT '',
  phone text DEFAULT '',
  email text DEFAULT '',
  emergency text DEFAULT '',
  emergency_rel text DEFAULT '',
  agency text DEFAULT '',
  bank_name text DEFAULT '',
  account_number text DEFAULT '',
  account_holder text DEFAULT '',
  welfare text DEFAULT 'none',
  rent numeric DEFAULT 0,
  maintenance_fee numeric DEFAULT 0,
  deposit numeric DEFAULT 0,
  due_date integer DEFAULT 10,
  contract_start date,
  contract_end date,
  file_name text DEFAULT '',
  file_data text DEFAULT '',
  status text DEFAULT 'active' CHECK (status IN ('active','ended'))
);
ALTER TABLE contracts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Authenticated users can CRUD" ON contracts FOR ALL USING (auth.role() = 'authenticated');

-- 5. meters
CREATE TABLE IF NOT EXISTS meters (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  unit_id bigint REFERENCES units(id) ON DELETE CASCADE,
  date date NOT NULL DEFAULT CURRENT_DATE,
  electricity numeric DEFAULT 0,
  water numeric DEFAULT 0
);
ALTER TABLE meters ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Authenticated users can CRUD" ON meters FOR ALL USING (auth.role() = 'authenticated');

-- 6. bills
CREATE TABLE IF NOT EXISTS bills (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  unit_id bigint REFERENCES units(id) ON DELETE CASCADE,
  year_month text NOT NULL DEFAULT '',
  rent numeric DEFAULT 0,
  maintenance_fee numeric DEFAULT 0,
  electricity numeric DEFAULT 0,
  water numeric DEFAULT 0,
  common_fee numeric DEFAULT 0,
  tv_fee numeric DEFAULT 0,
  late_fee numeric DEFAULT 0,
  total numeric DEFAULT 0,
  status text DEFAULT 'unpaid' CHECK (status IN ('unpaid','paid','pending')),
  due_date integer DEFAULT 10,
  elec_usage numeric DEFAULT 0,
  water_usage numeric DEFAULT 0
);
ALTER TABLE bills ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Authenticated users can CRUD" ON bills FOR ALL USING (auth.role() = 'authenticated');

-- 7. payments
CREATE TABLE IF NOT EXISTS payments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bill_id bigint REFERENCES bills(id) ON DELETE CASCADE,
  unit_id bigint REFERENCES units(id) ON DELETE CASCADE,
  amount numeric DEFAULT 0,
  date date NOT NULL DEFAULT CURRENT_DATE,
  source text DEFAULT 'manual' CHECK (source IN ('manual','prepaid','deposit'))
);
ALTER TABLE payments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Authenticated users can CRUD" ON payments FOR ALL USING (auth.role() = 'authenticated');

-- 8. prepaids
CREATE TABLE IF NOT EXISTS prepaids (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  unit_id bigint REFERENCES units(id) ON DELETE CASCADE,
  amount numeric DEFAULT 0,
  balance numeric DEFAULT 0,
  created_at timestamptz DEFAULT now()
);
ALTER TABLE prepaids ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Authenticated users can CRUD" ON prepaids FOR ALL USING (auth.role() = 'authenticated');

-- 9. deposit_deductions
CREATE TABLE IF NOT EXISTS deposit_deductions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  unit_id bigint REFERENCES units(id) ON DELETE CASCADE,
  amount numeric DEFAULT 0,
  reason text DEFAULT '',
  date date NOT NULL DEFAULT CURRENT_DATE,
  created_at timestamptz DEFAULT now()
);
ALTER TABLE deposit_deductions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Authenticated users can CRUD" ON deposit_deductions FOR ALL USING (auth.role() = 'authenticated');

-- 10. notices
CREATE TABLE IF NOT EXISTS notices (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL DEFAULT '',
  content text DEFAULT '',
  date date NOT NULL DEFAULT CURRENT_DATE,
  sent boolean DEFAULT false
);
ALTER TABLE notices ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Authenticated users can CRUD" ON notices FOR ALL USING (auth.role() = 'authenticated');

-- 11. inquiries
CREATE TABLE IF NOT EXISTS inquiries (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  unit_id bigint,
  unit_name text DEFAULT '',
  user_name text DEFAULT '',
  title text NOT NULL DEFAULT '',
  content text DEFAULT '',
  reply text DEFAULT '',
  replied_at date,
  created_at timestamptz DEFAULT now()
);
ALTER TABLE inquiries ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Authenticated users can CRUD" ON inquiries FOR ALL USING (auth.role() = 'authenticated');

-- 12. 초기 관리자 계정 생성 함수
CREATE OR REPLACE FUNCTION create_initial_admin()
RETURNS void AS $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM users WHERE role = 'admin') THEN
    INSERT INTO users (username, name, email, role, status)
    VALUES ('admin', '관리자', 'admin@kanseokro.com', 'admin', 'active');
  END IF;
END;
$$ LANGUAGE plpgsql;
